
issuer: https://manager.workshop:5554/dex
storage:
  type: sqlite3
  config:
    file: /config/dex.db

# HTTP service configuration
web:
  http: 0.0.0.0:5556
  https: 0.0.0.0:5554
  tlsCert: /config/ssl/dex.cert
  tlsKey: /config/ssl/dex.key

# Dex UI configuration
frontend:
  issuer: dex
#  logoURL: theme/logo.png
#   dir: ""
  theme: light

# Telemetry configuration
# telemetry:
#   http: 127.0.0.1:5558

logger:
  level: "debug"
  format: "text" # can also be "json"


connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: ldap:1686
    # insecureNoSSL: true
    insecureSkipVerify: true
    # startTLS: true
    rootCA: /config/ca.crt
    bindDN: cn=admin,dc=example,dc=org
    bindPW: ${PASSWORD}
    usernamePrompt: SSO Username
    userSearch:
      baseDN: ou=users,dc=example,dc=org
      filter: "(objectClass=person)"
      username: uid
      idAttr: uid
      emailAttr: mail
      # Maps to display name of users. No default value.
      nameAttr: cn
      preferredUsernameAttr: uid

    # Group search queries for groups given a user entry.
    groupSearch:
      # BaseDN to start the search from. It will translate to the query
      # "(&(objectClass=group)(member=<user uid>))".
      baseDN: ou=groups,dc=example,dc=org
      # Optional filter to apply when searching the directory.
      filter: "(objectClass=posixGroup)"
      userMatchers:
      - userAttr: uid
        groupAttr: memberUid
      nameAttr: cn

# OAuth2 configuration
oauth2:
#   # use ["code", "token", "id_token"] to enable implicit flow for web-only clients
  responseTypes: ["code", "token", "id_token"] # also allowed are "token" and "id_token"
#
#   # By default, Dex will ask for approval to share data with application
#   # (approval for sharing data from connected IdP to Dex is separate process on IdP)
  skipApprovalScreen: true
#
#   # If only one authentication method is enabled, the default behavior is to
#   # go directly to it. For connected IdPs, this redirects the browser away
#   # from application to upstream provider such as the Google login page
  alwaysShowLoginScreen: false
#
#   # Uncomment to use a specific connector for password grants
  passwordConnector: ldap

# Enable the password database.
#
# It's a "virtual" connector (identity provider) that stores
# login credentials in Dex's store.
enablePasswordDB: true

#'http://127.0.0.1:5555/callback'
staticClients:
  - id: kubernetes
    redirectURIs:
    - 'http://localhost:8000'
    - 'http://localhost:18000'
    name: 'Kubernetes'
    secret: aGVsbG9fZnJpZW5kCg==