srvconfig:
    debug: "256"
    adminpasswordfile: /config/passfile
    ldapport: "1389"
    srvtls:
        ldapsport: "1686"
        ldapstls:
            cafile: "/config/ca.crt"
            crtfile: "/config/ldap.crt"
            crtkeyfile: "/config/ldap.key"
database:
    - base: "dc=example,dc=org"
schemas:
    - path: "/config/schemas/guacConfigGroup.schema"
    - path: "/config/schemas/rfc2307bis.schema"
    - path: "/config/schemas/sudo.schema"
modules:
    - name: unique
    - name: pw-sha2
    - name: ppolicy
