version: '2.3'

services:
  telegraf:
    container_name: telegraf
    image: telegraf:1.18
    environment:
      - HOST_PROC=/host/proc
    privileged: true
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmp:/var/run/utmp
